# Generated by Django 4.2.8 on 2024-06-24 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(blank=True, default='', max_length=100)),
                ('Image', models.ImageField(blank=True, default='', upload_to='')),
                ('Information', models.TextField()),
                ('City', models.CharField(choices=[('kastoria', 'KASTORIA'), ('serres', 'SERRES')], default='kastoria', max_length=100)),
                ('Category', models.CharField(choices=[('nature', 'NATURE'), ('church', 'CHURCH'), ('museum', 'MUSEUM')], default='nature', max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
